addons:
  postgresql: "9.5"
services:
  - postgresql

language: go
go:
    - 1.12

install:
    - go get -u github.com/golang/lint/golint
    - go get -u github.com/mattn/goveralls

script:
   - make all check GO_BUILDFLAGS="-mod vendor"
   - $HOME/gopath/bin/goveralls -coverprofile=build/cover.out -service=travis-ci
